<?php

namespace Database\Seeders;

use Domain\Event\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'جشنواره نوروزی تهران',
                'summary' => 'جشنواره بزرگ نوروزی با برنامه‌های متنوع فرهنگی و هنری',
                'information' => 'جشنواره نوروزی تهران شامل نمایشگاه‌های هنری، کنسرت‌های موسیقی سنتی، کارگاه‌های آموزشی و برنامه‌های ویژه کودکان است.',
                'description' => 'این جشنواره هر ساله در آستانه سال نو برگزار می‌شود و هدف آن احیای فرهنگ و آداب و رسوم اصیل ایرانی است. برنامه‌های متنوعی از جمله نمایشگاه‌های هنری، کنسرت‌های موسیقی سنتی، کارگاه‌های آموزشی و برنامه‌های ویژه کودکان در این جشنواره ارائه می‌شود.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، میدان آزادی، پارک آزادی',
                'amount' => 'رایگان',
                'link' => 'https://example.com/noruz-festival',
                'email' => 'info@noruz-festival.ir',
                'phone' => '021-12345678',
                'website' => 'www.noruz-festival.ir',
                'facebook' => 'noruzfestival',
                'instagram' => 'noruzfestival',
                'youtube' => 'noruzfestival',
                'whatsapp' => '09123456789',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-03-20',
                'end_date' => '2025-04-02',
                'image' => '/images/events/noruz-festival.jpg',
                'slider_image' => '/images/events/noruz-festival-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'نمایشگاه بین‌المللی کتاب تهران',
                'summary' => 'بزرگترین نمایشگاه کتاب ایران با حضور ناشران داخلی و خارجی',
                'information' => 'نمایشگاه بین‌المللی کتاب تهران با حضور بیش از 2000 ناشر داخلی و خارجی برگزار می‌شود.',
                'description' => 'نمایشگاه بین‌المللی کتاب تهران یکی از بزرگترین رویدادهای فرهنگی ایران است که هر ساله با حضور بیش از 2000 ناشر داخلی و خارجی برگزار می‌شود. این نمایشگاه شامل بخش‌های مختلفی مانند کتاب‌های فارسی، عربی، انگلیسی و سایر زبان‌ها، نشریات، نرم‌افزارهای آموزشی و محصولات فرهنگی است.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، مصلی امام خمینی',
                'amount' => '50000 تومان',
                'link' => 'https://example.com/book-fair',
                'email' => 'info@bookfair.ir',
                'phone' => '021-98765432',
                'website' => 'www.bookfair.ir',
                'facebook' => 'tehranbookfair',
                'instagram' => 'tehranbookfair',
                'youtube' => 'tehranbookfair',
                'whatsapp' => '09187654321',
                'vip' => 1,
                'status' => 1,
                'priority' => 2,
                'start_date' => '2025-05-01',
                'end_date' => '2025-05-11',
                'image' => '/images/events/book-fair.jpg',
                'slider_image' => '/images/events/book-fair-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'کنفرانس فناوری اطلاعات و ارتباطات',
                'summary' => 'کنفرانس تخصصی در زمینه فناوری‌های نوین و دیجیتال',
                'information' => 'کنفرانس فناوری اطلاعات و ارتباطات با حضور متخصصان و کارشناسان برجسته حوزه IT برگزار می‌شود.',
                'description' => 'این کنفرانس تخصصی با هدف بررسی آخرین تحولات و نوآوری‌ها در حوزه فناوری اطلاعات و ارتباطات برگزار می‌شود. متخصصان و کارشناسان برجسته حوزه IT از سراسر کشور در این رویداد حضور خواهند داشت و آخرین دستاوردها و چالش‌های این حوزه را مورد بحث و بررسی قرار خواهند داد.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، مرکز همایش‌های بین‌المللی صدا و سیما',
                'amount' => '150000 تومان',
                'link' => 'https://example.com/ict-conference',
                'email' => 'info@ict-conference.ir',
                'phone' => '021-11223344',
                'website' => 'www.ict-conference.ir',
                'facebook' => 'ictconference',
                'instagram' => 'ictconference',
                'youtube' => 'ictconference',
                'whatsapp' => '09111223344',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-06-15',
                'end_date' => '2025-06-17',
                'image' => '/images/events/ict-conference.jpg',
                'slider_image' => '/images/events/ict-conference-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'جشنواره موسیقی سنتی ایران',
                'summary' => 'جشنواره موسیقی سنتی با اجرای هنرمندان برجسته موسیقی ایرانی',
                'information' => 'جشنواره موسیقی سنتی ایران با اجرای هنرمندان برجسته موسیقی ایرانی و گروه‌های موسیقی سنتی برگزار می‌شود.',
                'description' => 'جشنواره موسیقی سنتی ایران با هدف حفظ و اشاعه موسیقی اصیل ایرانی و معرفی هنرمندان جوان این حوزه برگزار می‌شود. در این جشنواره، هنرمندان برجسته موسیقی ایرانی و گروه‌های موسیقی سنتی از سراسر کشور به اجرای برنامه می‌پردازند و علاقه‌مندان می‌توانند از اجراهای متنوع و با کیفیت موسیقی سنتی بهره‌مند شوند.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، تالار وحدت',
                'amount' => '80000 تومان',
                'link' => 'https://example.com/traditional-music-festival',
                'email' => 'info@traditional-music.ir',
                'phone' => '021-55667788',
                'website' => 'www.traditional-music.ir',
                'facebook' => 'traditionalmusicfestival',
                'instagram' => 'traditionalmusicfestival',
                'youtube' => 'traditionalmusicfestival',
                'whatsapp' => '09155667788',
                'vip' => 1,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-07-10',
                'end_date' => '2025-07-20',
                'image' => '/images/events/traditional-music.jpg',
                'slider_image' => '/images/events/traditional-music-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'نمایشگاه صنایع دستی و هنرهای سنتی',
                'summary' => 'نمایشگاه تخصصی صنایع دستی و هنرهای سنتی ایران',
                'information' => 'نمایشگاه صنایع دستی و هنرهای سنتی ایران با حضور هنرمندان و صنعتگران سراسر کشور برگزار می‌شود.',
                'description' => 'این نمایشگاه تخصصی با هدف معرفی و فروش محصولات صنایع دستی و هنرهای سنتی ایران برگزار می‌شود. هنرمندان و صنعتگران از سراسر کشور در این نمایشگاه حضور دارند و محصولات متنوعی از جمله فرش، گلیم، سفال، شیشه، فلزکاری، چوب‌کاری و سایر هنرهای سنتی را عرضه می‌کنند.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، نمایشگاه بین‌المللی تهران',
                'amount' => '30000 تومان',
                'link' => 'https://example.com/handicrafts-exhibition',
                'email' => 'info@handicrafts-exhibition.ir',
                'phone' => '021-99887766',
                'website' => 'www.handicrafts-exhibition.ir',
                'facebook' => 'handicraftsexhibition',
                'instagram' => 'handicraftsexhibition',
                'youtube' => 'handicraftsexhibition',
                'whatsapp' => '09199887766',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-08-05',
                'end_date' => '2025-08-15',
                'image' => '/images/events/handicrafts-exhibition.jpg',
                'slider_image' => '/images/events/handicrafts-exhibition-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'سمینار کارآفرینی و کسب و کارهای نوپا',
                'summary' => 'سمینار تخصصی در زمینه کارآفرینی و راه‌اندازی کسب و کارهای نوپا',
                'information' => 'سمینار کارآفرینی و کسب و کارهای نوپا با حضور کارآفرینان موفق و متخصصان حوزه کسب و کار برگزار می‌شود.',
                'description' => 'این سمینار تخصصی با هدف آموزش و راهنمایی علاقه‌مندان به کارآفرینی و راه‌اندازی کسب و کارهای نوپا برگزار می‌شود. کارآفرینان موفق و متخصصان حوزه کسب و کار تجربیات خود را در اختیار شرکت‌کنندگان قرار می‌دهند و راهنمایی‌های لازم برای شروع و توسعه کسب و کار ارائه می‌شود.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، مرکز همایش‌های دانشگاه تهران',
                'amount' => '120000 تومان',
                'link' => 'https://example.com/entrepreneurship-seminar',
                'email' => 'info@entrepreneurship-seminar.ir',
                'phone' => '021-22334455',
                'website' => 'www.entrepreneurship-seminar.ir',
                'facebook' => 'entrepreneurshipseminar',
                'instagram' => 'entrepreneurshipseminar',
                'youtube' => 'entrepreneurshipseminar',
                'whatsapp' => '09122334455',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-09-20',
                'end_date' => '2025-09-22',
                'image' => '/images/events/entrepreneurship-seminar.jpg',
                'slider_image' => '/images/events/entrepreneurship-seminar-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'جشنواره فیلم کوتاه تهران',
                'summary' => 'جشنواره بین‌المللی فیلم کوتاه با حضور فیلمسازان ایرانی و خارجی',
                'information' => 'جشنواره بین‌المللی فیلم کوتاه تهران با حضور فیلمسازان ایرانی و خارجی و نمایش آثار برجسته سینمای کوتاه برگزار می‌شود.',
                'description' => 'جشنواره بین‌المللی فیلم کوتاه تهران یکی از مهم‌ترین رویدادهای سینمایی ایران است که با هدف معرفی و حمایت از فیلمسازان جوان و آثار برجسته سینمای کوتاه برگزار می‌شود. در این جشنواره، فیلمسازان ایرانی و خارجی آثار خود را به نمایش می‌گذارند و هیئت داوران متشکل از کارشناسان برجسته سینما، بهترین آثار را انتخاب و معرفی می‌کنند.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، سینما فلسطین',
                'amount' => '60000 تومان',
                'link' => 'https://example.com/short-film-festival',
                'email' => 'info@shortfilmfestival.ir',
                'phone' => '021-33445566',
                'website' => 'www.shortfilmfestival.ir',
                'facebook' => 'tehranshortfilmfestival',
                'instagram' => 'tehranshortfilmfestival',
                'youtube' => 'tehranshortfilmfestival',
                'whatsapp' => '09133445566',
                'vip' => 1,
                'status' => 1,
                'priority' => 2,
                'start_date' => '2025-10-15',
                'end_date' => '2025-10-25',
                'image' => '/images/events/short-film-festival.jpg',
                'slider_image' => '/images/events/short-film-festival-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'نمایشگاه گل و گیاه تهران',
                'summary' => 'نمایشگاه تخصصی گل و گیاه با انواع گونه‌های مختلف گیاهی',
                'information' => 'نمایشگاه گل و گیاه تهران با انواع گونه‌های مختلف گیاهی، گل‌های زینتی و ابزارهای باغبانی برگزار می‌شود.',
                'description' => 'نمایشگاه گل و گیاه تهران یکی از بزرگترین نمایشگاه‌های تخصصی در حوزه گل و گیاه است که با حضور تولیدکنندگان، فروشندگان و علاقه‌مندان به گل و گیاه برگزار می‌شود. در این نمایشگاه، انواع گونه‌های مختلف گیاهی، گل‌های زینتی، درختان و درختچه‌ها، ابزارهای باغبانی و محصولات مرتبط عرضه می‌شود.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، پارک ارم',
                'amount' => '25000 تومان',
                'link' => 'https://example.com/flower-exhibition',
                'email' => 'info@flower-exhibition.ir',
                'phone' => '021-44556677',
                'website' => 'www.flower-exhibition.ir',
                'facebook' => 'tehranflowerexhibition',
                'instagram' => 'tehranflowerexhibition',
                'youtube' => 'tehranflowerexhibition',
                'whatsapp' => '09144556677',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-11-10',
                'end_date' => '2025-11-20',
                'image' => '/images/events/flower-exhibition.jpg',
                'slider_image' => '/images/events/flower-exhibition-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'کنفرانس پزشکی و سلامت دیجیتال',
                'summary' => 'کنفرانس تخصصی در زمینه پزشکی دیجیتال و فناوری‌های سلامت',
                'information' => 'کنفرانس پزشکی و سلامت دیجیتال با حضور پزشکان، متخصصان حوزه سلامت و کارشناسان فناوری اطلاعات برگزار می‌شود.',
                'description' => 'این کنفرانس تخصصی با هدف بررسی آخرین تحولات و نوآوری‌ها در حوزه پزشکی دیجیتال و فناوری‌های سلامت برگزار می‌شود. پزشکان، متخصصان حوزه سلامت و کارشناسان فناوری اطلاعات از سراسر کشور در این رویداد حضور خواهند داشت و آخرین دستاوردها و چالش‌های این حوزه را مورد بحث و بررسی قرار خواهند داد.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، مرکز همایش‌های بیمارستان میلاد',
                'amount' => '200000 تومان',
                'link' => 'https://example.com/digital-health-conference',
                'email' => 'info@digital-health-conference.ir',
                'phone' => '021-66778899',
                'website' => 'www.digital-health-conference.ir',
                'facebook' => 'digitalhealthconference',
                'instagram' => 'digitalhealthconference',
                'youtube' => 'digitalhealthconference',
                'whatsapp' => '09166778899',
                'vip' => 1,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2025-12-05',
                'end_date' => '2025-12-07',
                'image' => '/images/events/digital-health-conference.jpg',
                'slider_image' => '/images/events/digital-health-conference-slider.jpg',
                'video' => null,
            ],
            [
                'title' => 'جشنواره غذاهای سنتی ایران',
                'summary' => 'جشنواره غذاهای سنتی ایران با معرفی انواع غذاهای محلی و سنتی',
                'information' => 'جشنواره غذاهای سنتی ایران با معرفی انواع غذاهای محلی و سنتی از سراسر کشور و آموزش پخت این غذاها برگزار می‌شود.',
                'description' => 'جشنواره غذاهای سنتی ایران با هدف معرفی و حفظ فرهنگ غذایی اصیل ایرانی و آموزش پخت انواع غذاهای محلی و سنتی از سراسر کشور برگزار می‌شود. در این جشنواره، آشپزهای محلی از سراسر کشور حضور دارند و انواع غذاهای سنتی را تهیه و عرضه می‌کنند. همچنین کارگاه‌های آموزشی پخت غذاهای سنتی نیز برگزار می‌شود.',
                'lat' => '35.6892',
                'long' => '51.3890',
                'address' => 'تهران، پارک ساعی',
                'amount' => '40000 تومان',
                'link' => 'https://example.com/traditional-food-festival',
                'email' => 'info@traditional-food-festival.ir',
                'phone' => '021-77889900',
                'website' => 'www.traditional-food-festival.ir',
                'facebook' => 'traditionalfoodfestival',
                'instagram' => 'traditionalfoodfestival',
                'youtube' => 'traditionalfoodfestival',
                'whatsapp' => '09177889900',
                'vip' => 0,
                'status' => 1,
                'priority' => 1,
                'start_date' => '2026-01-15',
                'end_date' => '2026-01-25',
                'image' => '/images/events/traditional-food-festival.jpg',
                'slider_image' => '/images/events/traditional-food-festival-slider.jpg',
                'video' => null,
            ],
        ];

        foreach ($events as $eventData) {
            Event::create($eventData);
        }
    }
}